import { UniverseChainId } from 'uniswap/src/features/chains/types'
// Import tokens from hardcodedPools to avoid duplication
import { NUSD, TFC, USDC, WCBTC, cUSD } from './hardcodedPools'

// Hardcoded Citrea tokens for the explore page with market data
export const HARDCODED_CITREA_TOKENS = [
  {
    id: WCBTC.address,
    chain: UniverseChainId.CitreaTestnet,
    address: WCBTC.address,
    symbol: WCBTC.symbol,
    name: WCBTC.name,
    decimals: WCBTC.decimals,
    project: { name: WCBTC.name },
    price: 95000,
    pricePercentChange1Hour: 0.5,
    pricePercentChange1Day: 2.3,
    volume1Day: { value: 150000 },
    marketCap: { value: 1900000000 },
  },
  {
    id: TFC.address,
    chain: UniverseChainId.CitreaTestnet,
    address: TFC.address,
    symbol: TFC.symbol,
    name: TFC.name,
    decimals: TFC.decimals,
    project: { name: TFC.name },
    price: 3.2,
    pricePercentChange1Hour: -0.8,
    pricePercentChange1Day: 5.7,
    volume1Day: { value: 45000 },
    marketCap: { value: 32000000 },
  },
  {
    id: cUSD.address,
    chain: UniverseChainId.CitreaTestnet,
    address: cUSD.address,
    symbol: cUSD.symbol,
    name: cUSD.name,
    decimals: cUSD.decimals,
    project: { name: cUSD.name },
    price: 0.999,
    pricePercentChange1Hour: 0.01,
    pricePercentChange1Day: -0.05,
    volume1Day: { value: 85000 },
    marketCap: { value: 85000000 },
  },
  {
    id: NUSD.address,
    chain: UniverseChainId.CitreaTestnet,
    address: NUSD.address,
    symbol: NUSD.symbol,
    name: NUSD.name,
    decimals: NUSD.decimals,
    project: { name: NUSD.name },
    price: 1.001,
    pricePercentChange1Hour: 0.02,
    pricePercentChange1Day: 0.1,
    volume1Day: { value: 62000 },
    marketCap: { value: 62000000 },
  },
  {
    id: USDC.address,
    chain: UniverseChainId.CitreaTestnet,
    address: USDC.address,
    symbol: USDC.symbol,
    name: USDC.name,
    decimals: USDC.decimals,
    project: { name: USDC.name },
    price: 1.0,
    pricePercentChange1Hour: 0.0,
    pricePercentChange1Day: 0.01,
    volume1Day: { value: 120000 },
    marketCap: { value: 120000000 },
  },
]
