name: "Tag and release"
on:
  workflow_dispatch:

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: 🧷️ Get version
        uses: juliangruber/read-file-action@v1
        id: version
        with:
          path: VERSION

      - name: 🧾️ Get release notes
        uses: juliangruber/read-file-action@v1
        id: release-notes
        with:
          path: RELEASE

      - name: 🏷️ Tag
        id: github-tag-action
        uses: uniswap/github-tag-action@7bddacd4864a0f5671e836721db60174d8a9c399
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.content }}
          tag_prefix: ""

      - name: 🪽 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.github-tag-action.outputs.new_tag }}
          name: Release ${{ steps.github-tag-action.outputs.new_tag }}
          body: ${{ steps.release-notes.outputs.content }}
